name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  provider: ^6.1.2
  json_annotation: ^4.0.0
  supabase_flutter: ^2.5.1

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
  assets:
    - assets/avatar_1.png
    - assets/avatar_2.png
    - assets/avatar_3.png
    - assets/avatar_4.png
    - assets/avatar_5.png
    - assets/avatar_6.png
    - assets/avatar_7.png
    - assets/thumbnail_1.png
    - assets/thumbnail_2.jpg
    - assets/gym1.jpg
    - assets/gym2.jpg
    - assets/gym3.jpg
    - assets/gym4.jpg
    - assets/background1.jpg
    - assets/background2.jpg
    - assets/background3.jpg